ui:
  image:
    full: hydrosphere/hydro-serving-ui:3.0.5
manager:
  image:
    full: hydrosphere/serving-manager:3.0.5
  depconfig: |-
    default-deployment-configuration = """
      {
        "name":"default",
        "hpa":{
            "minReplicas":1,
            "maxReplicas":10,
            "cpuUtilization":80
        },
        "container":{
            "resources":{
              "requests":{
                "cpu": "250m",
                "memory": "500m"
              }
            }
        },
        "pod":{
          "tolerations":[{
                "key":"node-type",
                "operator":"Equal",
                "value":"dev",
                "effect":"NoSchedule"
          }]
        }
      }
    """
gateway:
  image:
    full: hydrosphere/serving-gateway:3.0.5
sonar:
  image:
    full: hydrosphere/sonar:3.0.5
visualization:
  image:
    full: hydrosphere/hydro-visualization:3.0.5
auto-od:
  image:
    full: hydrosphere/hydro-auto-od:7fbecd2d284a4213bbc26eb61145a0f1fadb7d36
stat:
  image:
    full: hydrosphere/hydro-stat:3.0.5
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:3.0.5
postgresql:
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
global:
  ui:
    ingress:
      enabled: true
      host: "hydro-serving.dev.hydrosphere.io"
      grpchost: "hydro-grpc.dev.hydrosphere.io"
  registry:
    insecure: false
    ingress:
      enabled: true
      host: "hydro-registry.dev.hydrosphere.io"
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-1" # region for s3

  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "dev"
      effect: "NoSchedule"
